
//0
//1
//1
//65007
//ALPHA 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Reflection;
using System.Windows;

[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1.1.65007")]
[assembly: AssemblyInformationalVersion("0.1 ALPHA")]
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None, //where theme specific resource dictionaries are located
                                     //(used if a resource is not found in the page,
                                     // or application resource dictionaries)
    ResourceDictionaryLocation.SourceAssembly //where the generic resource dictionary is located
                                              //(used if a resource is not found in the page,
                                              // app, or any theme specific resource dictionaries)
)]
